apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
  namespace: app-server
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      containers:
        - name: app-server
          image: dixluwn/ict30001-test:latest
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: app-server-service
  namespace: app-server
  labels: 
    app: app-server
spec:
  type: LoadBalancer
  selector:
    app: app-server
  ports:
    - port: 3000