apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      containers:
        - name: app-server
          image: dixluwn/ict30001-mexer:6a88cdd7780acc9cb3f3b62a33a2730d2e64f4b5
          ports:
            - containerPort: 3000