apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      containers:
        - name: app-server
          image: dixluwn/ict30001-mexer:c3eb47b95e2ad30ac372f73938e22f52a4bdda5d
          ports:
            - containerPort: 80