apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      containers:
        - name: app-server
          image: dixluwn/ict30001-test:3910ccd5a30457cf4fd0608a92c736b77f250914
          ports:
            - containerPort: 80