apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      containers:
        - name: app-server
          image: dixluwn/ict30001-test:a98d8f357064822025a73d8b52b0e5f510b1cb42
          ports:
            - containerPort: 80