apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server-deployment
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: app-server
  template:
    metadata:
      name: app-server
      labels: 
        app: app-server
    spec:
      containers:
        - name: app-server
          image: dixluwn/ict30001-test:98b25c0a142e319278d794e3bd7839a982abd1b4
          ports:
            - containerPort: 80