name: Node.js CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Get current date with timezone
      id: date
      env:
        TZ: Asia/Ho_Chi_Minh
      run: echo "::set-output name=CURRENT_DATE::$(date +'%Y-%m-%d-%H-%M-%S')"
      
    - name: Build Docker Image
      run: docker build -t ci-pipeline .

    - name: Tagging Image as latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker tag ci-pipeline:latest ${DOCKER_USERNAME}/mexer-frontend:latest

    - name: Pushing to Dockerhub with latest version
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker push ${DOCKER_USERNAME}/mexer-frontend:latest

    - name: Tag Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker tag ci-pipeline:latest ${DOCKER_USERNAME}/mexer-frontend:${{ steps.date.outputs.CURRENT_DATE }}
    - name: Push Docker Image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker push ${DOCKER_USERNAME}/mexer-frontend:${{ steps.date.outputs.CURRENT_DATE }}