name: Test CI Flow

on:
    push:
      branches: 
        - main
    workflow_dispatch: {}

jobs:
    test-image:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        
        - name: Build and push test Docker image
          working-directory: ./Application/App1
          run: |
            docker build . -t ${{ secrets.DOCKER_USERNAME }}/ict30001-test
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
            docker push ${{ secrets.DOCKER_USERNAME }}/ict30001-test 
    